-----Automating and Data Transformation using 'TASK' on External stage-----
USE DATABASE CR_PL;
CREATE
OR REPLACE SCHEMA PL_CR_INFO;
--- All the customers with validated data
CREATE
OR REPLACE TASK PL_CR_INFO.TASK_CR_VALIDATED WAREHOUSE = COMPUTE_WH SCHEDULE = '1 MINUTE' AS CREATE
OR REPLACE TABLE PL_CR_INFO.CR_VALIDATED AS
SELECT
        *
FROM
        CR_PL.PUBLIC.CUSTOMER_VALIDATED;
--Customers opted for promotions
CREATE
OR REPLACE TASK PL_CR_INFO.TASK_CR_PROMO WAREHOUSE = COMPUTE_WH AFTER PL_CR_INFO.TASK_CR_VALIDATED AS CREATE
OR REPLACE TABLE PL_CR_INFO.CR_PROMO AS
SELECT
        *
FROM
        CR_PL.PUBLIC.CUSTOMER_VALIDATED
WHERE
        PROMOOPTIN = 'TRUE';
--Active customers
CREATE
OR REPLACE TASK PL_CR_INFO.TASK_CR_ACTIVE WAREHOUSE = COMPUTE_WH AFTER PL_CR_INFO.TASK_CR_PROMO AS CREATE
OR REPLACE TABLE PL_CR_INFO.CR_ACTIVE AS
SELECT
        *
FROM
        CR_PL.PUBLIC.CUSTOMER_VALIDATED
WHERE
        CUSTOMERSEGMENT = 'Active Customers';
-----Validating and running tasks
SHOW TASKS;
ALTER TASK PL_CR_INFO.TASK_CR_VALIDATED RESUME;
ALTER TASK PL_CR_INFO.TASK_CR_PROMO RESUME;
ALTER TASK PL_CR_INFO.TASK_CR_ACTIVE RESUME;
ALTER TASK PL_CR_INFO.TASK_CR_VALIDATED SUSPEND;
ALTER TASK PL_CR_INFO.TASK_CR_PROMO SUSPEND;
ALTER TASK PL_CR_INFO.TASK_CR_ACTIVE SUSPEND;
SELECT
        *
FROM
        CR_VALIDATED;
SELECT
        *
FROM
        CR_PROMO;
SELECT
        *
FROM
        CR_ACTIVE;
SELECT
        system$task_dependents_enable('TASK_CR_VALIDATED');